## OPS need info to do health check, please discuss with OPS before changing them.
#info:
#  app:
#    name: ${APP_NAME:bitfye-wallet}
#    check: ${APP_CHECK:NOT_SET}
#  env:
#    name: ${ENV_NAME:NOT_SET}
#  hostname: ${HOSTNAME:NOT_SET}
#  captain:
#    seq: ${CAPTAIN_SEQ:NOT_SET}
#    gen: ${CAPTAIN_GEN:NOT_SET}
#  build:
#    name: ${BUILD_APP_NAME:NOT_SET}
#    git:
#      version: ${BUILD_GIT_VERSION:NOT_SET}
#      hash: ${BUILD_GIT_HASH:NOT_SET}
#    time: ${BUILD_TIME:NOT_SET}
#    timestamp: ${BUILD_TIMESTAMP:NOT_SET}
#
#spring:
#  application:
#    name: ${PROJECT:bitfye-wallet}
#  profiles:
#    active: ${ENV_NAME:test-1}
#    include:
#      - ${ENV_PROFILE:default}

#app:
#  id: bitfye-wallet
#apollo:
#  meta: http://47.242.107.232:8080
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true
#    namespaces: application.yaml
#  cluster: default

server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: bitfye-wallet
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bitfye?allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    # 初始化，最小，最大连接数
    initialSize: 20
    minIdle: 20
    maxActive: 200
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    druid:
      web-stat-filter:
        session-stat-enable: false

# 需要改造进行加密处理
cobo:
  apiKey: 032730060f719d7251f6530e0027a2ed2c6e78b09dbcb7e841444d950caa5caf53
  apiSecret: a425cf8873d6b5bf35b76eba23a488b395f75b84179185949f23f233d12739fa

bitfye:
  generator:
    prefix: bitfye-wallet
  security:
    signatures:
      risk:
        host: http://127.0.0.1:8081
        appid: ctbergeVKRxpqxIJeaX
        appkey: oA44ASXwer3MJygZkxPqR666Zc3SaVq5LkfZM9ouer
        url:
          withdrawVerify: /v1/risk/withdrawVerify
      wallet:
        appid: 1OTLHR7UIDDFC1QAG5YG
        appkey: Mk1Oqf7buibn5OQPPLw6OgWe9PyqbmRrqm20Z2lG
redisson:
  address: redis://127.0.0.1:6379
  password:
  database: 0

logging:
  config: "classpath:logback-spring.xml"

mybatis-plus:
  mapper-locations: classpath*:/com/bitfye/common/mapper/impl/*Mapper.xml
  typeAliasesPackage: com.bitfye.common.model
  type-enums-package: com.bitfye.common.base.enums
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    db-config:
      table-prefix: "t_"
      id-type: auto
      table-underline: true
      column-format: "f_%s"
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
